# Generated by Django 2.2.5 on 2019-11-06 05:39

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='상품명')),
                ('photo1', models.ImageField(upload_to=API.models.Good.date_upload_to)),
                ('photo2', models.ImageField(upload_to=API.models.Good.date_upload_to)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('code', models.CharField(max_length=128, verbose_name='상품코드')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'trackline_shop',
            },
        ),
    ]
