# Generated by Django 2.2.5 on 2019-11-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={},
        ),
        migrations.AlterModelTable(
            name='good',
            table=None,
        ),
    ]
