# Generated by Django 2.2.5 on 2019-11-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20191106_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품들'},
        ),
        migrations.AlterModelTable(
            name='good',
            table='API_good',
        ),
    ]
